#!/bin/bash
##SBATCH --job-name=run06
##SBATCH --partition=gen
##SBATCH --constraint=rome
##SBATCH --nodes=1
##SBATCH --ntasks-per-node=128
##SBATCH --cpus-per-task=1
##SBATCH --time=00:10:00

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=40

module load adri_gcc
module load adri_base
source /mnt/home/aduivenvoorden/.pyenv/versions/enki/bin/activate

TAG=run07
ANADIR=/mnt/home/aduivenvoorden/local/cca_project/scripts
ODIR=/mnt/home/aduivenvoorden/project/so/20240521_sbi_bmode/${TAG}
SPECDIR=/mnt/home/aduivenvoorden/local/cca_project/data
CONFIGDIR=/mnt/home/aduivenvoorden/local/cca_project/scripts/configs

CONFIG=${CONFIGDIR}/config06.yaml

export JAX_ENABLE_X64=True
export JAX_DEBUG_NANS=True
export JAX_PLATFORMS=cpu

srun -u -n 1 python ${ANADIR}/check_cov.py --odir ${ODIR} --config ${CONFIG} --specdir ${SPECDIR}
