#!/bin/bash
#SBATCH --job-name=mcmc65t_test
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=72
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-core=1
#SBATCH --time=02:00:00

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

module purge
module load adri_gcc
module load adri_base
source $HOME/.pyenv/versions/sbi_bmode/bin/activate

TAG=mcmc65t_test
ANADIR=${HOME}/local/cca_project/scripts
ODIR=${HOME}/project/so/20240521_sbi_bmode/${TAG}
IDIR=${HOME}/project/so/20240521_sbi_bmode/run65t
SPECDIR=${HOME}/local/cca_project/data
CONFIGDIR=${HOME}/local/cca_project/scripts/configs
PYILCDIR=${HOME}/local/pyilc

CONFIG=${IDIR}/config.yaml
DATA=${IDIR}/data_draws_test_mf.npy
PARAMS=${IDIR}/param_draws_test.npy

export JAX_ENABLE_X64=True
#export JAX_DEBUG_NANS=True
export JAX_PLATFORMS=cpu 

SEED=0

srun -u --cpu-bind=cores -c $SLURM_CPUS_PER_TASK python ${ANADIR}/run_mcmc_basic.py --odir ${ODIR} --config ${CONFIG} --specdir ${SPECDIR} --data ${DATA} --seed ${SEED} --n_samples 4000 --n_chains 10 --params ${PARAMS}

cp ./slurm-${SLURM_JOB_ID}.out ${ODIR}/

