#!/bin/bash
#SBATCH --job-name=run03
#SBATCH --partition=gen
##SBATCH --constraint=rome
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=10
#SBATCH --time=02:00:00

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
#export OMP_NUM_THREADS=10

module load adri_gcc
module load adri_base
source /mnt/home/aduivenvoorden/.pyenv/versions/enki/bin/activate

TAG=run04
ANADIR=/mnt/home/aduivenvoorden/local/cca_project/scripts
ODIR=/mnt/home/aduivenvoorden/project/so/20240521_sbi_bmode/${TAG}
SPECDIR=/mnt/home/aduivenvoorden/local/cca_project/data

for r_true in 0.01 0.05
do
    for n_train in 1000
    do    
	srun -u --cpu-bind=cores -c $SLURM_CPUS_PER_TASK python ${ANADIR}/run_sbi_basic.py --odir ${ODIR} --specdir ${SPECDIR} --r_true ${r_true} --n_train ${n_train} --seed -1 --n_samples 10000 --n_rounds 3
    done
done

cp ./slurm-${SLURM_JOB_ID}.out ${ODIR}
