#!/bin/bash
##SBATCH --job-name=run36c_optuna
##SBATCH --nodes=1
##SBATCH --ntasks-per-node=72
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-core=1
##SBATCH --time=00:10:00

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=10

module purge
module load adri_gcc
module load adri_base
source $HOME/.pyenv/versions/sbi_bmode/bin/activate

TAG=run36c_optuna
ANADIR=${HOME}/local/cca_project/scripts
ODIR=${HOME}/project/so/20240521_sbi_bmode/${TAG}
IDIR=${HOME}/project/so/20240521_sbi_bmode/run36c

CONFIG=${IDIR}/config.yaml
PARAMS=${IDIR}/param_draws_round_000.npy
DATA=${IDIR}/data_draws_round_000.npy
DATA_OBS=${IDIR}/data_norm.npy
JOURNAL=${ODIR}/optuna_study.journal

export JAX_ENABLE_X64=True
export JAX_DEBUG_NANS=True
export JAX_PLATFORMS=cpu 

#srun -u --cpu-bind=cores -c $SLURM_CPUS_PER_TASK python ${ANADIR}/check_estimators.py --params ${PARAMS} --data ${DATA} --data-obs ${DATA_OBS} --odir ${ODIR} --config ${CONFIG}
srun -u -n 7 python ${ANADIR}/check_estimators.py --params ${PARAMS} --data ${DATA} --data-obs ${DATA_OBS} --odir ${ODIR} --config ${CONFIG} --journal ${JOURNAL}

#cp ./slurm-${SLURM_JOB_ID}.out ${ODIR}/
