#!/bin/bash
#SBATCH --job-name=run34a
#SBATCH --partition=preempt
##SBATCH --partition=gen
#SBATCH --qos=preempt
#SBATCH --constraint=rome
#SBATCH --nodes=6
##SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
##SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=02:00:00
##SBATCH --time=00:50:00

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
#export OMP_NUM_THREADS=1

module load adri_gcc
module load adri_base
source /mnt/home/aduivenvoorden/.pyenv/versions/enki/bin/activate

TAG=run34a
ANADIR=/mnt/home/aduivenvoorden/local/cca_project/scripts
ODIR=/mnt/home/aduivenvoorden/project/so/20240521_sbi_bmode/${TAG}
SPECDIR=/mnt/home/aduivenvoorden/local/cca_project/data
CONFIGDIR=/mnt/home/aduivenvoorden/local/cca_project/scripts/configs
PYILCDIR=/mnt/home/aduivenvoorden/local/pyilc

CONFIG=${CONFIGDIR}/config13.yaml

export JAX_ENABLE_X64=True
export JAX_DEBUG_NANS=True
export JAX_PLATFORMS=cpu 

NROUNDS=1
NTRAIN_PER_ROUND=5376
#NTRAIN_PER_ROUND=128
FID_BETA=1.5
FID_T=19.6

srun -u --cpu-bind=cores -c $SLURM_CPUS_PER_TASK python ${ANADIR}/run_sbi_basic.py --odir ${ODIR} --config ${CONFIG} --specdir ${SPECDIR} --n_train ${NTRAIN_PER_ROUND} --n_samples 50000 --n_rounds ${NROUNDS} --pyilcdir ${PYILCDIR} --fiducial_beta ${FID_BETA} --fiducial_T_dust ${FID_T} --deproj_dust --deproj_dbeta --use_dbeta_map --no-coadd-equiv-crosses

cp ./slurm-${SLURM_JOB_ID}.out ${ODIR}/
