#!/bin/bash
#SBATCH --job-name=run86_beta_extra
#SBATCH --nodes=12
#SBATCH --ntasks-per-node=72
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-core=1
#SBATCH --time=01:00:00

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

module purge
module load adri_gcc
module load adri_base
source $HOME/.pyenv/versions/sbi_bmode/bin/activate

TAG=run86_beta_extra
ANADIR=${HOME}/local/cca_project/scripts
ODIR=${HOME}/project/so/20240521_sbi_bmode/${TAG}
SPECDIR=${HOME}/local/cca_project/data
CONFIGDIR=${HOME}/local/cca_project/scripts/configs
PYILCDIR=${HOME}/local/pyilc

CONFIG=${CONFIGDIR}/config30.yaml

ODIR_PREV=${HOME}/project/so/20240521_sbi_bmode/run86_beta
PREV_DATA=${ODIR_PREV}/data_draws_round_000.npy
PREV_PARAMS=${ODIR_PREV}/param_draws_round_000.npy
DATA_MEAN=${ODIR_PREV}/data_mean.npy
DATA_STD=${ODIR_PREV}/data_std.npy
DATA_OBS=${ODIR_PREV}/data_norm.npy

export JAX_ENABLE_X64=True
export JAX_DEBUG_NANS=True
export JAX_PLATFORMS=cpu 

WAVELET_TYPE="TopHatHarmonic"
NROUNDS=1
NTRAIN_PER_ROUND=25920
FID_BETA=1.5
FID_T=19.6
FID_BETA_SYNC=-5.0
NTEST=0
SEED=1

srun -u --cpu-bind=cores -c $SLURM_CPUS_PER_TASK python ${ANADIR}/run_sbi_basic.py --odir ${ODIR} --config ${CONFIG} --specdir ${SPECDIR} --n_train ${NTRAIN_PER_ROUND} --n_samples 50000 --n_rounds ${NROUNDS} --pyilcdir ${PYILCDIR} --fiducial_beta ${FID_BETA} --fiducial_T_dust ${FID_T} --fiducial_beta_sync ${FID_BETA_SYNC} --deproj_dust --deproj_dbeta --deproj_sync --deproj_dbeta_sync --use_dbeta_map --use_sync_map --use_dbeta_sync_map --seed ${SEED} --n_test ${NTEST} --wavelet-type ${WAVELET_TYPE} --max-num-epochs 100 --previous-data ${PREV_DATA} --previous-params ${PREV_PARAMS} --data-obs ${DATA_OBS} --data-mean ${DATA_MEAN} --data-std ${DATA_STD}

cp ./slurm-${SLURM_JOB_ID}.out ${ODIR}/
