#!/bin/bash
#SBATCH --job-name=obsmat_spec
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-core=1
#SBATCH --time=00:30:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=yenbinhpy308@gmail.com
#SBATCH --mem=32GB

source /mpcdf/modules/init/sh

module purge
module load gcc/16
module load impi/2021.18

export LD_LIBRARY_PATH="$I_MPI_ROOT/lib:$I_MPI_ROOT/opt/mpi/libfabric/lib:$HOME/local/lib:$LD_LIBRARY_PATH"
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OPENBLAS_NUM_THREADS=1

source /u/bing/sbi_bmode/.venv/bin/activate

export JAX_ENABLE_X64=True
export JAX_DEBUG_NANS=True
export JAX_PLATFORMS=cpu

SCRIPT=/u/bing/sbi_bmode/scratch/obsmat_spectra_comparison.py

srun -u --cpu-bind=cores -c $SLURM_CPUS_PER_TASK \
    python ${SCRIPT}

cp ./slurm-${SLURM_JOB_ID}.out /u/bing/sbi_bmode/scratch/